# Generated by Django 3.2.13 on 2022-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_author_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='naz',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
