# Generated by Django 3.2.13 on 2022-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220609_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokupka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70)),
                ('way', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('books', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
