# Generated by Django 3.2.13 on 2022-07-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220703_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='annotation',
            field=models.CharField(max_length=2000),
        ),
    ]
