# Generated by Django 3.2.13 on 2022-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_author_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='annotation',
            field=models.CharField(max_length=8000),
        ),
    ]
